typography_spectrum: 0.9501255026552826
color:
  brandColors: []
  brandStrength: 1
  lightness: 0.5607232437469065
  saturation: 0.8967145932838321
  rhythmicContrast: 0.9324189990293235
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Testsitenew
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: test
purpose: []
